# Creation Date: 01/21/2024 7:50 PM EDT
# Updates:
# Authors: Joseph Armstrong (armstrongjoseph08@gmail.com)
# file: `./core/export/export_as_maxpreps.py`
# Purpose: Tenative code for exporting a game in a format that works with 
#           MaxPreps.
################################################################################


def export_as_maxpreps():
    """ """
    columns = [
        "Jersey",
        "RushingNum",
        "RushingYards",
        "RushingLong",
        "ReceivingNum",
        "ReceivingYards",
        "ReceivingLong",
        "PassingComp",
        "PassingAtt",
        "PassingInt",
        "PassingYards",
        "PassingTD",
        "PassingLong",
        "OffensiveFumbles",
        "OffensiveFumblesLost",
        "Tackles",
        "Assists",
        "TotalTackles",
        "TacklesForLoss",
        "Sacks",
        "SacksYardsLost",
        "QBHurries",
        "INTs",
        "INTYards",
        "PassesDefensed",
        "BlockedPunts",
        "BlockedFG",
        "FumbleRecoveries",
        "FumbleRecoveryYards",
        "CausedFumbles",
        "PuntReturnNum",
        "PuntReturnYards",
        "PuntReturnLong",
        "PuntReturnFairCatches",
        "KickoffReturnNum",
        "KickoffReturnYards",
        "KickoffReturnLong",
        "TotalReturnYards",
        "PuntNum",
        "PuntYards",
        "PuntLong",
        "PuntInside20",
        "KickoffNum",
        "KickoffYards",
        "KickoffLong",
        "KickoffTouchbacks",
        "RushingTDNum",
        "ReceivingTDNum",
        "MiscTDNum",
        "TotalTDNum",
        "PATKickingMade",
        "PATKickingAtt",
        "PATKickingPoints",
        "PATRushingNum",
        "PATReceivingNum",
        "PATDefReturnNum",
        "TotalConversionPoints",
        "FGMade",
        "FGAttempted",
        "FGLong",
        "Safeties",
        "TotalPoints",
    ]
    raise NotImplementedError("This function has yet to be implemented in this version")